CREATE TABLE specialty(
   id        INTEGER  NOT NULL PRIMARY KEY 
  ,specialty VARCHAR(62) NOT NULL
);
INSERT INTO specialty(id,specialty) VALUES (1,'Dentist');
INSERT INTO specialty(id,specialty) VALUES (2,'Pulmonary Disease');
INSERT INTO specialty(id,specialty) VALUES (3,'Nurse Practitioner');
INSERT INTO specialty(id,specialty) VALUES (4,'Emergency Medicine');
INSERT INTO specialty(id,specialty) VALUES (5,'Family Practice');
INSERT INTO specialty(id,specialty) VALUES (6,'Ophthalmology');
INSERT INTO specialty(id,specialty) VALUES (7,'Counselor');
INSERT INTO specialty(id,specialty) VALUES (8,'Orthopedic Surgery');
INSERT INTO specialty(id,specialty) VALUES (9,'Endocrinology');
INSERT INTO specialty(id,specialty) VALUES (10,'Otolaryngology');
INSERT INTO specialty(id,specialty) VALUES (11,'Internal Medicine');
INSERT INTO specialty(id,specialty) VALUES (12,'Psychiatry');
INSERT INTO specialty(id,specialty) VALUES (13,'Physician Assistant');
INSERT INTO specialty(id,specialty) VALUES (14,'Dermatology');
INSERT INTO specialty(id,specialty) VALUES (15,'Specialist');
INSERT INTO specialty(id,specialty) VALUES (16,'Neurology');
INSERT INTO specialty(id,specialty) VALUES (17,'Critical Care (Intensivists)');
INSERT INTO specialty(id,specialty) VALUES (18,'Infectious Disease');
INSERT INTO specialty(id,specialty) VALUES (19,'Cardiology');
INSERT INTO specialty(id,specialty) VALUES (20,'Oral Surgery (dentists only)');
INSERT INTO specialty(id,specialty) VALUES (21,'Student in an Organized Health Care Education/Training Program');
INSERT INTO specialty(id,specialty) VALUES (22,'General Practice');
INSERT INTO specialty(id,specialty) VALUES (23,'Optometry');
INSERT INTO specialty(id,specialty) VALUES (24,'General Surgery');
INSERT INTO specialty(id,specialty) VALUES (25,'Obstetrics/Gynecology');
INSERT INTO specialty(id,specialty) VALUES (26,'Radiation Oncology');
INSERT INTO specialty(id,specialty) VALUES (27,'Neurosurgery');
INSERT INTO specialty(id,specialty) VALUES (28,'Hematology/Oncology');
INSERT INTO specialty(id,specialty) VALUES (29,'Preventive Medicine');
INSERT INTO specialty(id,specialty) VALUES (30,'Urology');
INSERT INTO specialty(id,specialty) VALUES (31,'Physical Medicine and Rehabilitation');
INSERT INTO specialty(id,specialty) VALUES (32,'Podiatry');
INSERT INTO specialty(id,specialty) VALUES (33,'Thoracic Surgery');
INSERT INTO specialty(id,specialty) VALUES (34,'Hospitalist');
INSERT INTO specialty(id,specialty) VALUES (35,'Nephrology');
INSERT INTO specialty(id,specialty) VALUES (36,'Gastroenterology');
INSERT INTO specialty(id,specialty) VALUES (37,'Anesthesiology');
INSERT INTO specialty(id,specialty) VALUES (38,'Pediatric Medicine');
INSERT INTO specialty(id,specialty) VALUES (39,'Plastic Surgery');
INSERT INTO specialty(id,specialty) VALUES (40,'Rheumatology');
INSERT INTO specialty(id,specialty) VALUES (41,'Psychiatry & Neurology');
INSERT INTO specialty(id,specialty) VALUES (42,'Osteopathic Manipulative Medicine');
INSERT INTO specialty(id,specialty) VALUES (43,'Neuropsychiatry');
INSERT INTO specialty(id,specialty) VALUES (44,'Surgical Oncology');
INSERT INTO specialty(id,specialty) VALUES (45,'Orthopaedic Surgery');
INSERT INTO specialty(id,specialty) VALUES (46,'Interventional Pain Management');
INSERT INTO specialty(id,specialty) VALUES (47,'Hematology');
INSERT INTO specialty(id,specialty) VALUES (48,'Allergy/Immunology');
INSERT INTO specialty(id,specialty) VALUES (49,'Diagnostic Radiology');
INSERT INTO specialty(id,specialty) VALUES (50,'CRNA');
INSERT INTO specialty(id,specialty) VALUES (51,'Plastic and Reconstructive Surgery');
INSERT INTO specialty(id,specialty) VALUES (52,'Certified Clinical Nurse Specialist');
INSERT INTO specialty(id,specialty) VALUES (53,'Registered Nurse');
INSERT INTO specialty(id,specialty) VALUES (54,'Cardiac Surgery');
INSERT INTO specialty(id,specialty) VALUES (55,'Rehabilitation Agency');
INSERT INTO specialty(id,specialty) VALUES (56,'Colon & Rectal Surgery');
INSERT INTO specialty(id,specialty) VALUES (57,'Family Medicine');
INSERT INTO specialty(id,specialty) VALUES (58,'Medical Oncology');
INSERT INTO specialty(id,specialty) VALUES (59,'Certified Nurse Midwife');
INSERT INTO specialty(id,specialty) VALUES (60,'Vascular Surgery');
INSERT INTO specialty(id,specialty) VALUES (61,'Colorectal Surgery (formerly proctology)');
INSERT INTO specialty(id,specialty) VALUES (62,'Pain Management');
INSERT INTO specialty(id,specialty) VALUES (63,'Naturopath');
INSERT INTO specialty(id,specialty) VALUES (64,'Pathology');
INSERT INTO specialty(id,specialty) VALUES (65,'Neuromusculoskeletal Medicine, Sports Medicine');
INSERT INTO specialty(id,specialty) VALUES (66,'Geriatric Medicine');
INSERT INTO specialty(id,specialty) VALUES (67,'Hospice and Palliative Care');
INSERT INTO specialty(id,specialty) VALUES (68,'Gynecological/Oncology');
INSERT INTO specialty(id,specialty) VALUES (69,'Cardiac Electrophysiology');
INSERT INTO specialty(id,specialty) VALUES (70,'Multispecialty Clinic/Group Practice');
INSERT INTO specialty(id,specialty) VALUES (71,'Hand Surgery');
INSERT INTO specialty(id,specialty) VALUES (72,'Physical Therapist');
INSERT INTO specialty(id,specialty) VALUES (73,'Surgery');
INSERT INTO specialty(id,specialty) VALUES (74,'Pharmacist');
INSERT INTO specialty(id,specialty) VALUES (75,'Maxillofacial Surgery');
INSERT INTO specialty(id,specialty) VALUES (76,'Legal Medicine');
INSERT INTO specialty(id,specialty) VALUES (77,'Sports Medicine');
INSERT INTO specialty(id,specialty) VALUES (78,'Clinical Pharmacology');
INSERT INTO specialty(id,specialty) VALUES (79,'Interventional Radiology');
INSERT INTO specialty(id,specialty) VALUES (80,'Unknown Physician Specialty Code');
INSERT INTO specialty(id,specialty) VALUES (81,'Clinic/Center');
INSERT INTO specialty(id,specialty) VALUES (82,'Nuclear Medicine');
INSERT INTO specialty(id,specialty) VALUES (83,'Sleep Medicine');
INSERT INTO specialty(id,specialty) VALUES (84,'Midwife');
INSERT INTO specialty(id,specialty) VALUES (85,'Licensed Clinical Social Worker');
INSERT INTO specialty(id,specialty) VALUES (86,'Homeopath');
INSERT INTO specialty(id,specialty) VALUES (87,'Addiction Medicine');
INSERT INTO specialty(id,specialty) VALUES (88,'Specialist/Technologist');
INSERT INTO specialty(id,specialty) VALUES (89,'Behavioral Analyst');
INSERT INTO specialty(id,specialty) VALUES (90,'Licensed Practical Nurse');
INSERT INTO specialty(id,specialty) VALUES (91,'Geriatric Psychiatry');
INSERT INTO specialty(id,specialty) VALUES (92,'Pharmacy Technician');
INSERT INTO specialty(id,specialty) VALUES (93,'Psychologist (billing independently)');
INSERT INTO specialty(id,specialty) VALUES (94,'Oral & Maxillofacial Surgery');
INSERT INTO specialty(id,specialty) VALUES (95,'General Acute Care Hospital');
INSERT INTO specialty(id,specialty) VALUES (96,'Hospital (Dmercs Only)');
INSERT INTO specialty(id,specialty) VALUES (97,'Preferred Provider Organization');
INSERT INTO specialty(id,specialty) VALUES (98,'Medical Genetics, Ph.D. Medical Genetics');
INSERT INTO specialty(id,specialty) VALUES (99,'Personal Emergency Response Attendant');
INSERT INTO specialty(id,specialty) VALUES (100,'Psychologist');
INSERT INTO specialty(id,specialty) VALUES (101,'Slide Preparation Facility');
INSERT INTO specialty(id,specialty) VALUES (102,'Neurological Surgery');
INSERT INTO specialty(id,specialty) VALUES (103,'Thoracic Surgery (Cardiothoracic Vascular Surgery)');
INSERT INTO specialty(id,specialty) VALUES (104,'Chiropractic');
INSERT INTO specialty(id,specialty) VALUES (105,'Health Maintenance Organization');
INSERT INTO specialty(id,specialty) VALUES (106,'Unknown Supplier/Provider');
INSERT INTO specialty(id,specialty) VALUES (107,'Community Health Worker');
INSERT INTO specialty(id,specialty) VALUES (108,'Military Health Care Provider');
INSERT INTO specialty(id,specialty) VALUES (109,'Medical Genetics');
