# Generated by Django 3.2.8 on 2021-12-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentialName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'credential',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=150)),
                ('isOpioid', models.BooleanField()),
                ('drugId', models.IntegerField()),
            ],
            options={
                'db_table': 'drug',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('npi', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=4, null=True)),
                ('isOpiodPrescriber', models.BooleanField()),
                ('totalPrescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'prescriber',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialtyName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=2)),
                ('population', models.IntegerField()),
                ('death', models.IntegerField()),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Prescriber_Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugQuantity', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribers.drug')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribers.prescriber')),
            ],
            options={
                'db_table': 'prescriber_drug',
            },
        ),
        migrations.CreateModel(
            name='Prescriber_Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribers.credential')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribers.prescriber')),
            ],
            options={
                'db_table': 'prescriber_credential',
            },
        ),
        migrations.AddField(
            model_name='prescriber',
            name='presciber_drugs_field',
            field=models.ManyToManyField(through='prescribers.Prescriber_Drug', to='prescribers.Drug'),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='prescriber_credential_field',
            field=models.ManyToManyField(through='prescribers.Prescriber_Credential', to='prescribers.Credential'),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='specialtyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prescribers.specialty'),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prescribers.state'),
        ),
    ]
